### PR TITLE
adding fallback to grab entity id to name mapping from SGD

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — DISMISSED** [review]
Thanks @sweng66 !

There's some commented out code on 334 335 342 343, not sure if you'd want a comment about what it would be used for later, or just remove, but it's fine to just leave in.

**Comment by sweng66** [comment]
@azurebrd Good catch! I just removed these 4 commented old code. Thanks!

**Comment by sweng66** [comment]
@azurebrd Can you check it again? Thanks

**Review by azurebrd — APPROVED** [review]
Cool, thanks @sweng66 !

**Comment by sweng66** [comment]
Thanks @azurebrd

**Pull request merged**
