### PR TITLE
one off script for deleting duplicate mod_reference_type rows

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — DISMISSED** [review]
Thanks @sweng66 I see the SELECT orders by reference_id, and I imagine that it subselects by order it got written in, but it might be better to explicitly subselect by mod_reference_type_id to make sure it finds the earlier ones first and deletes the later ones.  Practically, I don't think it makes a difference, but it might make more sense if we're ever looking at the transactions.  (That a bunch of things that got INSERTed at creation don't have an MRT removed while something from a later update remained).  If you don't think it's worth it, that's fine with me, I realize it's functionally the same thing.

**Comment by sweng66** [comment]
@azurebrd This makes sense!! I fixed it. Thanks.

**Comment by sweng66** [comment]
@azurebrd and will fixed version against prod database when it is ready.

**Review by azurebrd — APPROVED** [review]
Awesome, thanks @sweng66 !

**Pull request merged**
