### PR TITLE
fix(tests): run-test-bash and run-functest do not delete all postgres dbs but only literature-test

### PR DESCRIPTION
**Pull request by valearna**

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
I don't really understand it, but cool

**Review by sweng66 — APPROVED** [review]
@valearna "docker-compose --env-file .env.test run --rm dev_app sh tests/init_test_db.sh"
what does "--rm" mean? delete the container after restarted database?

**Comment by valearna** [comment]
@sweng66 exactly, it means remove the container when it's done. I'm using it only to recreate the test db, so that if you have other dbs in the same postgres docker container they are not deleted

**Comment by sweng66** [comment]
@valearna I see! That is great.

**Pull request merged**
