### PR TITLE
Scrum 2665

### PR DESCRIPTION
**Pull request by valearna**
- new DB model
- modified API
- modified tests

### CODE REVIEW

**Comment by valearna** [comment]
Needs to generate alembic revision. Waiting for #411 to get merged to get the latest alembic file

**Review by azurebrd — APPROVED** [review]
Thanks @valearna !  I imagine this is mostly what you showed us yesterday, plus the alembic file, so I haven't looked through it again too carefully.

**Comment by valearna** [comment]
Thanks @azurebrd. Yes, I've added a couple of crud functions that were missing yesterday, but the overall structure hasn't changed

**Comment by sweng66** [comment]
https://github.com/alliance-genome/agr_literature_service/blob/SCRUM-2665/agr_literature_service/api/crud/topic_entity_tag_crud.py#L36

This is not a big deal, but if we use "filter_by", we can save some typing, I meant we can get rid of all these "TopicEntityTagModel"

**Comment by sweng66** [comment]
ignore my comment since majority of codebase use "filter" instead of "filter_by"..

**Comment by sweng66** [comment]
https://github.com/alliance-genome/agr_literature_service/blob/SCRUM-2665/agr_literature_service/api/crud/topic_entity_tag_utils.py#L26

db.query(TopicEntityTagSourceModel).filter(
        TopicEntityTagSourceModel.topic_entity_tag_id == topic_entity_tag_source_id).one_or_none()

Assume TopicEntityTagSourceModel.topic_entity_tag_id is the primary key for "topic_entity_tag",  is the "topic_entity_tag_source_id" the primary key for the source table (topic_entity_tag_source)?

**Comment by sweng66** [comment]
@valearna Overall the code looks great! Thanks.

**Review by sweng66 — DISMISSED** [review]

**Comment by valearna** [comment]
I always prefer `filter` instead of `filter_by` because mypy and flake8 can check the column names

**Comment by valearna** [comment]
They do with `filter`, but in `filter_by` you can put any name and it's not directly linked to the model so they won't know

**Comment by valearna** [comment]
It's totally fine to use `filter_by`, it's only a matter of personal preference

**Review by sweng66 — APPROVED** [review]
Looks great! Thanks @valearna

**Pull request merged**
