### PR TITLE
SCRUM-2096 find_unparsable_date_published now updates reference table…

### PR DESCRIPTION
**Pull request by azurebrd**
… to populate date_published_start and date_published_end.  Does not update version table.  Uses raw sql would take nearly 100 times longer with sqlalchemy.

### CODE REVIEW

**Review by sweng66 — APPROVED** [review]
Looks great! Thanks @azurebrd 

Can you update the date_published_start and  date_published_end at the same time? I know this is not a big deal for updating a small set of data.

**Review by valearna — APPROVED** [review]
looks good, thanks @azurebrd!

**Comment by azurebrd** [comment]
> Looks great! Thanks @azurebrd
> 
> Can you update the date_published_start and date_published_end at the same time? I know this is not a big deal for updating a small set of data.

@sweng66 Oh, I didn't know that was an option !  I'll try it, thanks !

**Comment by sweng66** [comment]
@azurebrd Great!

**Review by sweng66 — APPROVED** [review]
great!! Thanks @azurebrd

**Pull request merged**
