### PR TITLE
Scrum 4170 - validating entities based on entity_id_validation

### PR DESCRIPTION
**Pull request by valearna**
* added WB validation
* refactored code to avoid duplications

### CODE REVIEW

**Review by sweng66 — DISMISSED** [review]
Looks good! Thanks @valearna

**Review by azurebrd — COMMENTED** [review]
@sweng66 @valearna Do we need to put SGD_API_URL and WB_API_URL in the .env  so we know that it needs to be added in the filesystem version ?

topic_entity_tag_crud.py has a commented out import in line 36 we probably don't need, but it's fine

**Comment by sweng66** [comment]
@azurebrd both suggestions (adding WB/SGD URLs to .env and removing the line36 from tet crud) sound good to me.

**Comment by valearna** [comment]
Yes, thanks @azurebrd ! I'll add them to the .env file

**Review by azurebrd — APPROVED** [review]
Thanks for the changes @valearna !

**Comment by valearna** [comment]
Thanks @azurebrd and @sweng66

**Pull request merged**
