### PR TITLE
Scrum 2165

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Comment by sweng66** [comment]
Looks great! Thanks @azurebrd 

usually I would add the following after line80
db_session.add(x)
I didn't know it would work without it.

**Review by sweng66 — APPROVED** [review]

**Comment by azurebrd** [comment]
@sweng66 Oh.  I think it worked ?  I mean, I think I saw the db change afterward.  @valearna do you know if that should work ?

**Comment by sweng66** [comment]
@azurebrd I believe you. I just didn't know that before.

**Comment by azurebrd** [comment]
@sweng66 It's kind of late, I was just starting to doubt whether I'd set things backwards in the data (at first it was backward, because I was checking that the wrong thing was still on 3002), and I was checking the wrong thing :P  The logs make sense though.  Thanks :)

**Comment by sweng66** [comment]
I see.

**Pull request merged**
