### PR TITLE
Scrum 3095 - new api to get list of reference with referencefile ids to be processed by textpresso

### PR DESCRIPTION
**Pull request by valearna**

### CODE REVIEW

**Review by sweng66 — DISMISSED** [review]
Looks great! Thanks @valearna 

BTW, do we need "source_is_pmc" in line 772 and 776 in reference_crud.py?

**Review by azurebrd — DISMISSED** [review]
Cool, didn't know you could just r.curie > something, I guess it's because it's 0 padded.  Thanks @valearna !

**Comment by sweng66** [comment]
@azurebrd we can also order by title. basically any strings

**Comment by azurebrd** [comment]
*nod*  thanks @sweng66 :)

**Comment by valearna** [comment]
Thanks @sweng66 and @azurebrd. You are right @sweng66 we don't need that data structure anymore. I removed it

**Comment by valearna** [comment]
@azurebrd the curies follow alphanumeric order, so we can use string comparison to know if a curie is larger than another. All new curies will come after the old ones and search is O(logn) since the field is indexed with a btree.

**Review by azurebrd — APPROVED** [review]
Thanks both

**Review by sweng66 — APPROVED** [review]
Thanks @valearna

**Pull request merged**
