### PR TITLE
adding RGD to dqm loading pipeline, adding 'medline' and 'sici' to ignore-id-list for xml-to-json script

### PR DESCRIPTION
**Pull request by sweng66**
and fixes to make sure XREF prefixes are removed before comparing data from db and from json, and some other random fixes for lit_processing scripts.

### CODE REVIEW

**Review by valearna — APPROVED** [review]
Everything looks good to me, even though I'm not very familiar with this pipeline

**Comment by sweng66** [comment]
Thanks for looking over the fixes @valearna

**Review by azurebrd — APPROVED** [review]
Great, thanks @sweng66 !

**Comment by sweng66** [comment]
Thanks ! @valearna

**Comment by sweng66** [comment]
@azurebrd Thanks Juancarlos for checking out this PR.

**Pull request merged**
