### PR TITLE
Scrum 2284 - added support for multiple referencefiles (file metadata) for the same md5sum

### PR DESCRIPTION
**Pull request by valearna**

### CODE REVIEW

**Comment by sweng66** [comment]
op.drop_index('idx_md5sum', table_name='referencefile')

op.create_index('idx_md5sum', 'referencefile', ['md5sum'], unique=False)

so we need these two commands to drop this index. right? I thought first one will do that?

**Comment by valearna** [comment]
Thanks for taking a look at this PR so wuickly @sweng66. I kept a non-unique index on md5sum since we want to search referencefiles (also) by md5sum and with an index the queries will be much faster

**Review by azurebrd — APPROVED** [review]
That's great, thanks @valearna !

**Comment by sweng66** [comment]
@valearna Oh I see. It is an index, not unique key. Makes sense

**Review by azurebrd — APPROVED** [review]

**Pull request merged**
