### PR TITLE
Import refactor

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://agr-jira.atlassian.net/browse/SCRUM-1444

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
That's great @dougli1sqrd !  I'll defer to Valerio on whether to merge or not, as I don't really understand all of it and what might need testing or what-not.  Thanks

**Comment by azurebrd** [comment]
@FB-ping says "Seems bugs with branch import_refactor when try to insert mod_corpus_associations, unable to test other endpoint without this function working."  @dougli1sqrd can you look into it ?   The functional tests don't test for mod_corpus_association because I'm still modifying the xml_processing to do the changes, and then the functional tests to test that those endpoints work.  We could also use some unit tests for the mod and mod_corpus_association endpoints.

**Comment by azurebrd** [comment]
@FB-ping says : it works fine to insert/update mods, but got errors when try to insert mod_corpus_associations.
@azurebrd says : 
Eric: to test inserting a mod_corpus_association you'll need an existing mod though, so create at least one mod first.  e.g.
{
  "abbreviation": "FB",
  "short_name": "FlyBase",
  "full_name": "FlyBase"
}
Then you can create a mod_corpus_association with
{
  "mod_abbreviation": "FB",
  "mod_corpus_sort_source": "mod_pubmed_search",
  "corpus": true,
  "reference_curie": "AGR:AGR-Reference-0000000001"
}
But you'll need the reference first, so under the reference endpoint create one with just a title and category
{
  "title": "test title",
  "category": "research_article"
}

**Comment by dougli1sqrd** [comment]
Looks like everything here is above board. Running the tests locally passed, as well as a manual test worked.

**Review by valearna — APPROVED** [review]
The changes look good, thanks @dougli1sqrd. I tested the branch locally on an empty database and I can see the version tables and was able to create a reference, a mod, and mod_corpus_associations. I also tested it by connecting to rdsdev and was able to show some references.

**Pull request merged**
