### PR TITLE
Scrum 2153

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Comment by azurebrd** [comment]
@valearna @sweng66 I've got some temporary stuff in there to delete before final merge.  Valerio, we can talk tomorrow and clean this up, but it's basically working off of your populate_test_mod_reference_types fixture code.  Also, unittests were failing earlier, before I did anything, so I don't know how that got into main.

**Review by sweng66 — APPROVED** [review]
Looks great! @azurebrd

**Comment by sweng66** [comment]
I am lazy so I usually use filter_by() to save some typing.

rt_obj = db_session.query(ReferenceTypeModel).filter_by(label = reference_type).one_or_none()

and 

rt_obj = db_session.query(ReferenceTypeModel).filter(ReferenceTypeModel.label == reference_type).one_or_none()

will return the same info.

**Comment by sweng66** [comment]
BTW, looks great! No need to change anything.

**Comment by azurebrd** [comment]
Good to know, thanks @sweng66 !

**Review by valearna — APPROVED** [review]
It looks great @azurebrd!

**Review by valearna — APPROVED** [review]

**Pull request merged**
