### PR TITLE
Refactoring docs

### PR DESCRIPTION
**Pull request by nuin**
Third time is a charm ...

### CODE REVIEW

**Comment by nuin** [comment]
Same as previous PR.

**Review by azurebrd — CHANGES_REQUESTED** [review]
generate_pubmed_nlm_resource.py  has been renamed again instead of copied, but otherwise looks good.

**Comment by nuin** [comment]
strange, I will double check. Is it OK to add the version from `main`?

**Comment by azurebrd** [comment]
@nuin Yeah, the one in main should be good

**Review by azurebrd — APPROVED** [review]

**Pull request merged**
