### PR TITLE
Adding a new report to PubMed Search

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
cool !  (fyi, Ceri's going to ask for some minor change in wording, so could hold off on merging, or could merge and do a separate PR later for that)

**Comment by sweng66** [comment]
Ok. I will wait. Thanks @azurebrd for looking over the code!

**Comment by sweng66** [comment]
Will merge now. Fix any wording changes later.

**Comment by azurebrd** [comment]
Thanks @sweng66 :)

**Pull request merged**
