### PR TITLE
isort configuration added to pyproject.toml

### PR DESCRIPTION
**Pull request by nuin**

### CODE REVIEW

**Review by ianlongden — COMMENTED** [review]
Can we add:-

[tool.isort]
multi_line_output = 3

to the toml file please. pretty please.

**Comment by nuin** [comment]
I thought `hugs` would do that, but I will add it

**Review by ianlongden — APPROVED** [review]

**Comment by ianlongden** [comment]
Are hugs different to cuddles ?

Sorry its been a long week and its only Thursday!!!

-Ian.

**Comment by nuin** [comment]
It depends on where on the commonwealth you are, I guess

**Pull request merged**
