### PR TITLE
adding check to make sure the okta user have permission to delete the Tet row

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Oh, there was already oktaAccess.ALL_ACCESS, that's great.

Weird about mypy...
Might be good to leave some commented out code that it should be 403, but it's 404 because mypy ?  Wonder how that passed mypy before, if this wasn't changed.

Thanks Shuai.

**Comment by sweng66** [comment]
@azurebrd Sounds great to leave the old code (but comment it out)

**Review by azurebrd — APPROVED** [review]
Thanks @sweng66

**Comment by sweng66** [comment]
Thanks! @azurebrd

**Pull request merged**
