### PR TITLE
fixed to set logger in report_utils module so no need to pass the log…

### PR DESCRIPTION
**Pull request by sweng66**
…ger from other programs

### CODE REVIEW

**Review by valearna — COMMENTED** [review]
It seems that some modules have `logger = logging.getLogger()` without name. Can you make sure all modules define their logger with `logger = logging.getLogger(__name__)` @sweng66 ?

**Comment by sweng66** [comment]
Sure @valearna

**Comment by sweng66** [comment]
@valearna fixed =)

**Review by valearna — APPROVED** [review]
Cool, thanks @sweng66. It looks great!

**Comment by sweng66** [comment]
Thanks for looking over the code! @valearna

**Pull request merged**
