### PR TITLE
adding XB to the update list, clean up argparse

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by valearna — COMMENTED** [review]
The PR Looks good. I wonder whether we should define the list of mods in a single location or read them from the DB. Any thoughts @azurebrd @ianlongden ?

**Review by valearna — APPROVED** [review]

**Review by azurebrd — APPROVED** [review]
@valearna Yeah, we do have a hardcoded list of mods in a bunch of scripts and a bunch of places in the UI.  In the UI sometimes they need to be the abbreviation vs the curie prefix, so we'd need to extend the mod table to have a curie_prefix column first.

Edit: or at least define the list of mods in a separate file in one place and import that.

**Comment by sweng66** [comment]
We have 'GO' in the mod table. Are we going to store the GO related data in the database? 

we can fix the data dumping and pubmed update scripts to get a list of mod abbreviations (excluding 'GO') from  the database.. but still need to hardcode 'GO' in the code unless we are adding a new column to mark that in the mod table.

**Comment by sweng66** [comment]
@azurebrd Thanks for checking out the fix!!

**Comment by azurebrd** [comment]
Oh, yeah, good point, GO is not meaningful for the lit_processing, but is still a mod.

**Pull request merged**
