### PR TITLE
SCRUM-1243 Take endpoint to query all cross_references, extract all c…

### PR DESCRIPTION
**Pull request by azurebrd**
…urie prefixes, match to MODs, generate a mod_corpus_association entry, post to API that does not exist yet, when ready update to work properly

### CODE REVIEW

**Comment by nuin** [comment]
I have some changes to suggest, will do on GitHub

**Comment by azurebrd** [comment]
Hi @FB-ping .  This would be the simple way to post to the database one-by-one using the existing xml processing helper modules to generate the okta token and post to the API.  It downloads all the reference cross_references from the API endpoint and processes them, but since we don't yet know the final format for creating a mod_corpus_association, we'll have to update this once we do.

**Comment by azurebrd** [comment]
@nuin This is a one time script that we'll run once the API for mod_corpus_association is live.  It will only run once, and we'll never use it again.  We'll probably do some modified version for the md5sum script, once that's ready to be worked on.  It's probably not worth spending a lot of time to make this really nice, but if you wanted to make a generic future-processing-to-api script, that's probably good.  (That said, feel free to make suggestions / improvements)

**Review by nuin — APPROVED** [review]

**Comment by nuin** [comment]
Of course flake8 comes back to bite me, sorry

**Review by azurebrd — COMMENTED** [review]
I like the changes, thanks @nuin !

**Review by nuin — APPROVED** [review]

**Comment by azurebrd** [comment]
Thanks, @nuin !

**Pull request merged**
