### PR TITLE
adding code to transition WFT to 'file uploaded' or 'file upload in progress' when uploading a main PDF in API

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I don't really know, I'll defer to @valearna

**Comment by sweng66** [comment]
Thanks @azurebrd

**Review by valearna — APPROVED** [review]
Thanks @sweng66 !

**Comment by sweng66** [comment]
Thanks @valearna

**Pull request merged**
