### PR TITLE
re-factored the nested aggregation code and ..

### PR DESCRIPTION
**Pull request by sweng66**
1. adding a new authorNameAnalyzer for authors mapping
 2. fixed the code to use new analyzer when searching for author names so users can use english keyboard to search author names with accented letters.
 3. fixed search unit tests to work with the new analyzer
 4. fixed the crontab schedule for interaction papers loading from 6AM to 6PM PST

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I'll defer to Valerio :)

**Comment by sweng66** [comment]
Thanks for checking this out =) @azurebrd

**Review by valearna — APPROVED** [review]
Everything looks good to me, thanks @sweng66 !

**Comment by sweng66** [comment]
Thanks ! @valearna

**Pull request merged**
