### PR TITLE
upgrade kafka, debezium, ksql version, fix make_subset

### PR DESCRIPTION
**Pull request by FB-ping**
the DEBEZIUM version in this file /usr/share/agr_env_files/.env.rdsdev_4001, before merge this PR, I will change the DEBEZIUM version here.

### CODE REVIEW

**Comment by valearna** [comment]
this looks great @FB-ping. Can we test this on stage before merging?

**Comment by FB-ping** [comment]
@valearna yes, first edit /usr/share/agr_env_files/.env.rdsdev_4001,  then restart api/debezium from branch scrum-4462-upgrade-ksql-debezium,  I can test this on weekend.

**Comment by valearna** [comment]
That's awesome, thanks @FB-ping, I'll approve on Monday if everything looks good

**Comment by FB-ping** [comment]
@valearna so we are done with testing and can merge now ?

**Comment by valearna** [comment]
Yes, this is now ready to be merged. Thanks a lot @FB-ping!

**Review by valearna — APPROVED** [review]

**Comment by valearna** [comment]
This is still not working on stage. We should roll back to the previous software version. Closing this PR

**Pull request closed without merging**
