### PR TITLE
Autocomplete XRefs endpoint for WB

### PR DESCRIPTION
**Pull request by valearna**
Using DB queries instead of Elasticsearch

### CODE REVIEW

**Review by sweng66 — APPROVED** [review]
Looks great! Thanks @valearna

**Review by azurebrd — APPROVED** [review]
Looks good, thanks @valearna .  When I was working on the Sort endpoint, that was under search, and we changed it to a query, so I thought about moving it to a Query endpoint, but you (Valerio) suggested moving it to a Sort endpoint, which is where it's at now.  Should this be in the cross_reference/ section in a similar way ?

**Comment by valearna** [comment]
Thanks @azurebrd. Yes, moving it to the xref router makes sense

**Review by azurebrd — APPROVED** [review]
Cool, thanks @valearna !

**Pull request merged**
