### PR TITLE
FB now has ISBN: cross_references

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Comment by azurebrd** [comment]
New FB data has ISBNs in cross_references.  No one before had sent cross_references, and because the data was messy before, new types have to be added to a whitelist.

**Review by gildossantos — APPROVED** [review]

**Comment by azurebrd** [comment]
Thanks @gildossantos !

**Comment by nuin** [comment]
I was later, sorry @azurebrd

**Comment by azurebrd** [comment]
@nuin no no, not at all, thanks Paulo.

**Pull request merged**
