### PR TITLE
adding a new column (taxon_ids) into mod table

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I'm not sure how this was supposed to work.  Were we also going to track the default taxon somehow ?

**Comment by sweng66** [comment]
We will need to create an end point to return the mod to taxonIDs mapping and also update the UI to get rid of hard-coded taxon ID to species name mapping and instead to get the mapping from API. @azurebrd

**Comment by azurebrd** [comment]
Sounds good @sweng66 , so this is just one part.  But do we still need somewhere in the database a place to set which taxon is the default taxon ?

**Comment by sweng66** [comment]
It is set when we applied the alembic file @azurebrd

**Review by valearna — APPROVED** [review]
Looks good, thanks @sweng66!

**Comment by sweng66** [comment]
Thanks @valearna

**Pull request merged**
