### PR TITLE
adding code to update citation

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by valearna — APPROVED** [review]
Everything looks good to me, thanks @sweng66

**Review by ianlongden — COMMENTED** [review]
That's a lot of code when I could have simply added return True/False.

**Comment by sweng66** [comment]
@valearna @ianlongden Thanks for looking over the code!
@ianlongden The script already has the reference/author/resource data in the memory for generating the citation. While if the script is calling your citation update module, it will need to go to database to retrieve these data again for each updated paper.  It will probably slow down the PubMed updating program. I see your point that we have some repeating code here (eg format year and authors). Maybe I should fix the script to just directly call your citation update function. 

What do you all think?

**Comment by ianlongden** [comment]
Okay if there is a good reason then I am happy :-)

**Comment by azurebrd** [comment]
@ianlongden .  Valerio and Shuai were talking, and the plan is to rewrite citation_from_data to take in the author array and the date, then do the parsing into a string for all authors and the year, then the lit processing code can use the same function.  (Might have missed some details, but that's the general idea)

**Comment by ianlongden** [comment]
Makes sense. Thanks,

**Comment by sweng66** [comment]
@ianlongden I just fixed the 'get_citation_from_args' function in reference_crud.py so the command line scripts can also use it without repeating code. Can you check to make sure it won't mess up anything? I have tested and it worked fine for pubmed updating program. Thanks!

**Review by azurebrd — APPROVED** [review]
Thanks, @sweng66 !

**Comment by ianlongden** [comment]
That’s what the tests are for :-)
But thanks for checking with me.

-Ian.

**Pull request merged**
