### PR TITLE
SCRUM-1770 Adding Extra Fields

### PR DESCRIPTION
**Pull request by pjhale**
Adding xrefs, date published, abstract, and authors to search return.

Related to https://github.com/alliance-genome/agr_literature_ui/tree/SCRUM-1770

### CODE REVIEW

**Comment by pjhale** [comment]
@valearna So are these failed checks related to what you are working on with the alternative tests?  This is currently running on dev so I don't think there are any code related issues.

**Comment by azurebrd** [comment]
@pjhale The flake8 is usually formatting type stuff.  The unittest is because the API work usually has tests associated with it, and I haven't looked at the test, but it probably expects something and because of your changes, it's getting something else.  Valerio's new tests are still in development and aren't part of main / the current tests.  I think Valerio wrote the search related unit test, so he can probably help explain how to change / test things.

**Comment by valearna** [comment]
The errors are not related to my changes to the tests but they should be easy to fix:
1. It seems that there are some whitespaces missing that are braking flake8: https://github.com/alliance-genome/agr_literature_service/runs/8079926736?check_suite_focus=true
2. You need to add the new required fields to the test data in agr_literature_service/api/tests/test_014_search.py. The test data there don't have the new fields required by the `search_references` function

**Review by azurebrd — DISMISSED** [review]
Looks good to me, but I'll defer to @valearna

**Review by valearna — DISMISSED** [review]
Looks good, thanks @pjhale! You can merge into the main branch and delete this branch

**Review by valearna — APPROVED** [review]

**Pull request merged**
