### PR TITLE
fixing mypy errors

### PR DESCRIPTION
**Pull request by dougli1sqrd**
Simple fixes for mypy checks in the mod_association branch

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
Oh I see some errors in mypy still, weird that locally I don't see it

**Comment by azurebrd** [comment]
@dougli1sqrd The mypy errors in github actions can be fixed by merging main, which has an updated mypy.config that excludes that directory, until Paulo can come back to fix them (unless you want to also look into fixing those)
https://github.com/alliance-genome/agr_literature_service/runs/5727322914?check_suite_focus=true

**Comment by azurebrd** [comment]
Yeah, Valerio and I weren't seeing those mypy errors locally.  He think we should figure out how to have the same mypy environment locally and in github actions, but we don't know how.

**Comment by azurebrd** [comment]
Thanks @dougli1sqrd .  It looks good to me, but I'll defer to Pinglei and Valerio, who have actively worked on the branch.

**Comment by dougli1sqrd** [comment]
infinite flake8 errors, but mypy now fixed

**Pull request merged**
