### PR TITLE
Scrum 1999 - API changes to merge TET data

### PR DESCRIPTION
**Pull request by valearna**
- Merge TET entries during reference merge API call
- Revalidate tags of winning paper to account for possible cross-reference validation between tags from losing and winning refs
- Fixed date_updated management for note updates on duplicate tags with different note values
- Changed force_insertion behavior for TET API - now only forces insertion on different created_by users and not for the very same tag by the same user

### CODE REVIEW

**Review by sweng66 — APPROVED** [review]
Looks great! Thanks! @valearna

**Comment by valearna** [comment]
I have not yet tested this with a large number of TETs. I'll keep the PR open and add a specific webtest with a large number of tags

**Comment by valearna** [comment]
Thanks for the review @sweng66

**Comment by valearna** [comment]
Added a webtest for large merges. It took ~2m to merge 2 refs with 1k tets each. The time is used mostly to check for duplicates. I will try to optimize the create_tag function to see if we can get a bit faster

**Review by azurebrd — COMMENTED** [review]
Thanks @valearna !

**Comment by valearna** [comment]
Thanks @azurebrd @sweng66. This is ready for a final review

**Review by sweng66 — APPROVED** [review]

**Pull request merged**
