### PR TITLE
fix 1 bug for md5sum insert

### PR DESCRIPTION
**Pull request by FB-ping**

### CODE REVIEW

**Comment by sweng66** [comment]
I think everything is working fine so no need this fix! @FB-ping @valearna

**Comment by FB-ping** [comment]
@sweng66 @valearna Yes, without the change, it will fail to load new PMID , the SQL for null value insertion is wrong.

**Comment by azurebrd** [comment]
@FB-ping Shuai tested loading the data after Valerio's updates, and says that it worked well.  Do you have an example that doesn't work after Valerio's changes ?

**Comment by azurebrd** [comment]
The four of us talked, and everything's fine

**Pull request closed without merging**
