### PR TITLE
Scrum 2095

### PR DESCRIPTION
**Pull request by azurebrd**

### CODE REVIEW

**Comment by azurebrd** [comment]
@sweng66 @ianlongden @valearna I think this handles everything, including the unit tests, but when Valerio was talking about his changes and Shuai was pointing out things, I realized there's lots I don't know about the API, so please let me know if I missed something.
This doesn't cover updating existing scripts to generate and populate this data when creating or updating a paper.  I've messaged Ceri about creating a separate story about that.

**Review by sweng66 — APPROVED** [review]
Looks great! Thanks @azurebrd

**Comment by sweng66** [comment]
Yes, I can take care of the lit_processing scripts (including xml_to_json.py)

**Comment by sweng66** [comment]
We can go over about API tomorrow

**Comment by azurebrd** [comment]
Thanks so much @sweng66 !  I'll hold off on merging at least until Valerio sees the message about alembic_version

**Comment by sweng66** [comment]
Sounds good! @azurebrd

**Pull request merged**
