### PR TITLE
Scrum 3013 - added validation and display_tag to topic_entity_tags 

### PR DESCRIPTION
**Pull request by valearna**
- Added display_tag as a new column to the main topic_entity_tag table and removed the old qualifier table
- Added validation fields (author, curator, curation_tools)
- Added 'negated' field to source table to indicate positive/negative annotations
- Added automated validation on insertion/deletion of sources

### CODE REVIEW

**Comment by valearna** [comment]
We need to update the UI to work with the new fields

**Review by azurebrd — DISMISSED** [review]
Great, thanks @valearna !

**Comment by valearna** [comment]
This is ready for stage - it includes alembic changes

**Review by azurebrd — APPROVED** [review]
Great, thanks @valearna !

**Pull request merged**
