### PR TITLE
Scrum 4579 - do not set the file conversion to "failed" in case of network errors

### PR DESCRIPTION
**Pull request by valearna**

### CODE REVIEW

**Comment by sweng66** [comment]
Do we not want to set the job in progress or failed during the pdf to text conversion? when do we set the status? @valearna

**Comment by valearna** [comment]
@sweng66 at standup we decided that we won't add "in progress" for pdf2tei conversion and we don't need to change the status to "failed" in case of network errors so that we can try again at the next run

**Review by sweng66 — APPROVED** [review]
Looks good! Thanks @valearna

**Comment by valearna** [comment]
thanks @sweng66 !

**Pull request merged**
