### PR TITLE
Upload 6 pdfs for stage papers

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Thanks @sweng66 !

I would have thought that upload_pdf_file_to_s3 already existed somewhere and didn't need to be written, just imported.  But I don't actually know.  We don't ever need to upload to prod, just stage, and I see the cronjob does that, which made me think that this might be code that exists somewhere else.  

Thanks !

**Comment by sweng66** [comment]
@azurebrd You are right. We can use the available function!!! Thanks.

**Comment by sweng66** [comment]
wait. did you mean that we already have code some where that only uploads the files to s3 for stage papers? @azurebrd

**Review by azurebrd — APPROVED** [review]
No, I don't actually know, @sweng66 .  If the existing function is different than what you need for this task, then using a new function makes sense.  I just thought this function looked like something that already existed, since it also uploaded to prod.  The cronjob only running on stage/build makes sense

**Comment by sweng66** [comment]
@azurebrd I see. Thanks

**Pull request merged**
