### PR TITLE
Scrum 2381 - new analyzer for text fields

### PR DESCRIPTION
**Pull request by valearna**
- new analyzer based on punctuation followed by whitespace character
- curies still using autocomplete analyzer (same as A-team)

### CODE REVIEW

**Review by ianlongden — COMMENTED** [review]
It would be good to have a test with a wildcard in it.

**Comment by valearna** [comment]
Good point @ianlongden. I'll add it

**Review by ianlongden — APPROVED** [review]
I am no expert but looks okay and tests pass.

**Comment by valearna** [comment]
Thanks @ianlongden !

**Pull request merged**
