### PR TITLE
fixed to get rid of tests/ in the file path for false positive files …

### PR DESCRIPTION
**Pull request by sweng66**
…(just testing purpose

### CODE REVIEW

**Comment by azurebrd** [comment]
@sweng66 Wouldn't it be better to change that in line 135-138 
search_path = base_path + 'pubmed_searches/'
search_outfile_path = base_path + 'pubmed_searches/search_new_mods/'
pmc_process_path = base_path + 'pubmed_searches/pmc_processing/'
pmc_storage_path = base_path + 'pubmed_searches/pmc_processing/pmc_xml/'

Maybe make a xml_processing path = base_path.replace("tests/", "")  and use that instead of base_path in those 4 lines ?
I can't tell what pmc_storage_path and search_outfile_path are for, but maybe they're used by other scripts downstream ?

**Comment by sweng66** [comment]
@azurebrd Sounds good! Will do that. Initially, I thought this will only affect the input files.

**Review by azurebrd — CHANGES_REQUESTED** [review]
Oh, no, I meant, make a new variable as a copy of XML_PATH without tests, and use that for the path variables that concatenate pubmed_searches/   Because base_path is used later on for json_filepath, json_path, log_path, and other things, and those should probably still be off of base_path instead of this tests-less path.

**Comment by sweng66** [comment]
Is that just the original fix? just remove the 'tests/' from search_path if the 'tests' exists. @azurebrd

**Comment by azurebrd** [comment]
Well, on lines 135 to 138 you're creating path variables using pubmed_searches/ based on the base_path which comes from environ XML_PATH and removing tests/ from all base_path,  but I think there's multiple cases where it should use the base_path from XML_PATH including the tests/   so that if you're running tests, you're generating files and loading files from the tests/ directory, not from the xml_processing/ directory.  That's why I thought you wanted a separate variable from base_path just for the paths that have pubmed_searches/ and strip out 'tests/' just for those.

**Review by azurebrd — APPROVED** [review]
Thanks @sweng66 !

**Pull request merged**
