### PR TITLE
fixed TET create, MCA create and patch endpoints to add manual indexing workflow tags for SGD papers

### PR DESCRIPTION
**Pull request by sweng66**
* TET create endpoint will add "manual indexing complete" or  "manual indexing in progress" into the WFT table for SGD papers if the tag is not already there and if the index_wft is passed in.
* MCA create endpoint will add "manual indexing needed" into the WFT table for newly created SGD papers 
* MCA patch endpoint will add "manual indexing needed" into the WFT table for newly sorted in-corpus SGD papers
* fixed textpresso main pdf retrieval endpoint only return main pdf with pdf_type = 'pdf'
* globally fixed code to identify main pdfs based on pdf_type = 'pdf', file_class = 'main', and file_publication_status = 'final'
* also set default pdf_type to 'pdf' if it is a main pdf file and its pdf_type is not set
API fixes for SCRUM-4564, SCRUM-4587, & SCRUM-4583

### CODE REVIEW

**Review by FB-ping — DISMISSED** [review]
code look fine to me.

**Comment by sweng66** [comment]
Thanks @FB-ping

**Review by valearna — APPROVED** [review]
Looks good, thanks @sweng66

**Comment by sweng66** [comment]
Thanks @valearna

**Pull request merged**
