### PR TITLE
two files modified with black for checking

### PR DESCRIPTION
**Pull request by nuin**
I applied `black` on two files of the xml pipeline. More info on `black` here https://github.com/psf/black

Let me know if the changes are too disruptive, please don't merge this or don't approve if you don't want to have it set. Depending on opinions I can run on all other files.

Let me know

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I like the standardization of " instead of '
Things in ( ) that fit in one line converted to being in separate lines looks weird to me, but I guess I could get used to it.
Breaking a chain of if  x and y and z ... into separate lines (xml_to_json.py line 303 -> 353) looks even more weird.  I guess, this might be what @nuin was saying before, that you can have tons of functions that are all very small (was it like 3 or 5 lines each ?).  As it was, that function in xml_to_json.py was very long, and being able to see a lot of logic in one screen (because a line could have so much code) was helpful.  If we went with this, it might be easier to handle if it was refactored into a lot of small functions ?  It seems like a lot of work though, so I don't know what you were thinking for that (Paulo).
I'll go along with what most people want, but I'd probably be less inclined to work on code that has a lot of lines that are relatively empty (but I might get used to it)

**Review by dougli1sqrd — COMMENTED** [review]
Like in the other PR, I don't really think auto-formatters really buy us anything. I think, within reason, a variety of styles is fine and ultimately doesn't matter all that much.

I always worry that with auto-formatters we concentrate on the aesthetics of how the code looks and not enough on the structure and design, things that affect readability and maintainability a lot more than style.

**Comment by azurebrd** [comment]
@dougli1sqrd I'm also okay with the code being as it's been, but I haven't had to review someone else's code, so I can understand @nuin not wanting to look at how I formatted all those thousands of lines of xml_processing :P

**Comment by nuin** [comment]
The same as on the other PR, the code we are creating here someday might be used by other people and even other people might join the group. 

When you are working alone, doesn't matter the code style, documentation, etc, but when you are working in a team, some standardization might be necessary so a single standard can be used by everyone with ease and new members can learn and get acquainted with the code. Having worked on the UI and the lack of a proper documentation, not even comments in the code, one can understand the requirements for this. React enforces automatically some coding style, which helps decrease the learning curve, but still it's hard to understand some decisions.


In this repo, everyone, but @azurebrd and @adamjohnwright, is working on a someone else's code and in order to streamline things for us and for the future it would be great to have some coding standards. If you don't like standards, you can adapt to anything. If you like standards you can write your own and share with us @dougli1sqrd. 

Of course, there are advantages and disadvantages in using code styling apps, and you can find arguments online for either side.

**Pull request closed without merging**
