### PR TITLE
SCRUM-3047-General-Topic-Validation

### PR DESCRIPTION
**Pull request by pjhale**

### CODE REVIEW

**Comment by pjhale** [comment]
The test test_show_reference_referencefiles_referencefile_mods randomly failed in Valerio's last commit for no apparent reason... seems to be fixed now.  Working on adding some additional tests.

**Comment by azurebrd** [comment]
There were some tests that used to fail sometimes because some transactions weren't happen in the same order, and those were rewritten, but it's possible some tests are still doing that.  But also some tests just fail sometimes and there's no apparent reason, like you said.

**Comment by valearna** [comment]
I'm trying to fix the error with tests @pjhale

**Comment by pjhale** [comment]
thanks Valerio... moving this to ready for review.

**Review by valearna — APPROVED** [review]

**Pull request merged**
