### PR TITLE
Scrum 2856 rename reference comments and corrections

### PR DESCRIPTION
**Pull request by FB-ping**

### CODE REVIEW

**Review by sweng66 — COMMENTED** [review]
Looks good to me! Thanks @FB-ping
Another developer should look over.

**Review by sweng66 — APPROVED** [review]
Looks good to me! Thanks @FB-ping

**Comment by sweng66** [comment]
@valearna @azurebrd Can one of you take a look before merging the branch into main?

**Review by valearna — COMMENTED** [review]
I don't know much about reference relations. Is this work just renaming comments and corrections to relations or is there any new functionality?

**Comment by sweng66** [comment]
Just renaming @valearna

**Comment by sweng66** [comment]
I think we can merge it when UI part is ready. We can fix it if there is anything coming up. @FB-ping @valearna @azurebrd 
What do you think?

**Comment by FB-ping** [comment]
@sweng66 @valearna @azurebrd   I also have the UI ready (except the work to make new component for book/chapter), now I just filter out chaptin/haschapter.   If someone can review the UI PR, then we can merge both API and UI the same time.

**Pull request merged**
